replicaCount: 1

image:
  repository: bitnami/nginx
  # tag: "latest"   # optional; pin a version if you prefer

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: nginx-demo.cloudforge.home.arpa
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
  tls:
    - hosts:
        - nginx-demo.cloudforge.home.arpa
      secretName: nginx-demo-tls
resources: {}
