apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-demo-cert
  namespace: nginx-demo
spec:
  secretName: nginx-demo-tls
  dnsNames:
    - nginx-demo.cloudforge.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
