apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resume-cert
  namespace: resume
spec:
  secretName: resume-tls
  dnsNames:
    - resume.cloudforge.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
