apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # MULTIPLE SOURCES CONFIGURATION
  sources:
    # 1) Namespace + sealed secret yaml
    - repoURL: https://github.com/colinchaput/homelab-gitops.git
      targetRevision: HEAD
      path: apps/apps/netdata/manifests
    
    # 2: The Upstream Netdata Helm Chart
    - repoURL: https://netdata.github.io/helmchart/
      targetRevision: 3.7.153
      chart: netdata
      helm:
        values: |
          image:
            tag: stable
          
          # PARENT (Dashboard)
          parent:
            claiming:
              enabled: true
            # 'envFrom' loads the entire secret as environment variables
            envFrom:
              - secretRef:
                  name: netdata-claim

          # CHILD (Agents)
          child:
            claiming:
              enabled: true
            envFrom:
              - secretRef:
                  name: netdata-claim

  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
