apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://netdata.github.io/helmchart/
    targetRevision: stable
    chart: netdata
    helm:
      values: |
        image:
          tag: stable
        
        # Enable claiming, but keep fields empty (we inject them below)
        parent:
          claiming:
            enabled: true
        child:
          claiming:
            enabled: true

        # This tells Kubernetes: "Look at the secret named 'netdata-claim' 
        # and inject those values as Environment Variables for the pod"
        extraEnv:
          - name: NETDATA_CLAIM_TOKEN
            valueFrom:
              secretKeyRef:
                name: netdata-claim
                key: NETDATA_CLAIM_TOKEN
          - name: NETDATA_CLAIM_ROOMS
            valueFrom:
              secretKeyRef:
                name: netdata-claim
                key: NETDATA_CLAIM_ROOMS
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
