apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # MULTIPLE SOURCES CONFIGURATION
  sources:
    # 1) Namespace + sealed secret yaml
    - repoURL: https://github.com/colinchaput/homelab-gitops.git
      targetRevision: HEAD
      path: apps/apps/netdata/manifests
    
    # 2: The Upstream Netdata Helm Chart
    - repoURL: https://netdata.github.io/helmchart/
      targetRevision: 3.7.153
      chart: netdata
      helm:
        values: |
          image:
            tag: stable
          parent:
            claiming:
              enabled: true
          child:
            claiming:
              enabled: true
          # Connect the environment variables to your Sealed Secret
          extraEnv:
            - name: NETDATA_CLAIM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netdata-claim
                  key: NETDATA_CLAIM_TOKEN
            - name: NETDATA_CLAIM_ROOMS
              valueFrom:
                secretKeyRef:
                  name: netdata-claim
                  key: NETDATA_CLAIM_ROOMS
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
