apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # after cert-manager
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/colinchaput/homelab-gitops
    targetRevision: HEAD
    path: apps/platform/cert-manager-issuers/manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
