apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cloudforge-home-arpa
  namespace: monitoring
spec:
  secretName: wildcard-cloudforge-home-arpa-tls
  dnsNames:
    - "cloudforge.home.arpa"
    - "*.cloudforge.home.arpa"
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
