apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-stack-cert
  namespace: monitoring
spec:
  secretName: prometheus-stack-tls
  dnsNames:
    - grafana.cloudforge.home.arpa
    - prometheus.cloudforge.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
