apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall-cert
  namespace: apps-heimdall-homepage
spec:
  secretName: heimdall-tls
  dnsNames:
    - homepage.cloudforge.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
