apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: resume
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  sources:
    # 1) Helm chart from Bitnami over HTTPS
 #  - repoURL: oci://registry-1.docker.io/bitnamicharts    # OCI source can be used, but only if ArgoCD provided credentials for docker hub, since OCI requires auth
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      # Either pin a version OR omit to track latest from the repo:
      targetRevision: 22.2.3
      helm:
        valueFiles:
          - $values/apps/apps/resume/values.yaml

    # 2) Your Git repo providing the values.yaml
    - repoURL: https://github.com/colinchaput/homelab-gitops
      targetRevision: HEAD
      ref: values

      # 3) New: mount files for NGINX
    - repoURL: https://github.com/colinchaput/homelab-gitops
      targetRevision: HEAD
      path: apps/apps/nginx-demo/manifests
