replicaCount: 1

image:
  repository: bitnami/nginx
  # tag: "latest"   # optional; pin a version if you prefer

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: resume.cloudforge.home.arpa
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "false"
    nginx.ingress.kubernetes.io/hsts-max-age: "0"
  tls:
    - hosts:
        - resume.cloudforge.home.arpa
      secretName: resume-tls
resources: {}


# mount our server block + pdf
extraVolumes:
  - name: resume-server-block
    configMap:
      name: resume-server-block
  - name: resume-pdf
    configMap:
      name: resume-pdf

extraVolumeMounts:
  - name: resume-server-block
    mountPath: /opt/bitnami/nginx/conf/server_blocks/resume.conf
    subPath: resume.conf
    readOnly: true
  - name: resume-pdf
    mountPath: /opt/bitnami/nginx/html/resume.pdf
    subPath: resume.pdf
    readOnly: true
