---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-cloudflare-tunnel-remote
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # before cloudflared deployment (1)
spec:
  encryptedData:
    tunnelToken: AgDH/Jeidkh3VUAdkaCojKTEJP66Xu95ct+FmjIGPWGudVxJiObYlmskPA/CYcfZGcTt/Eb5R4kvZjZ1uwfNj4juZEjV3YfKj3Kw1LGvKQnUzhUEzPf78Dp+WaxV4Dg4UBuvhsjUIFfQoEO6HxVtaHQG0tMjUINbJ69lVcXSP3MI5LpV1hzU6pIygg06uMl/UmRWdoebrw0pBpMBCxxiB6FJ5DS66ttEl+Noq6cg+uMLa2PSL9qwNwKUwd3o1BMYAwAQMhzB6f/qzC35ZmY3yVRWlleGzs5buYj6PTEplGHRp/zq2o4O0oG7+7ImAIxmllqDaS07gYNU/Bbx3/cJJqqLnSAgYgxJHD/aPAVn2FrqMlU/8FW59kmmfjpvb10Ixau/Wlz7pAZPqqzKf3En7p/Y+NIfcObb89YNlNx0C54lnbUk8ucoSnWDz9g/IxUusQhT3iF7mrKUl8s6ZsDoIYlZCKtJ0LSGp0o6lYtVWlTKruUxEFkd08nq0vS/ZiPwp+3tnkXUFxiXuM3vog1tISXlWnhHQDFtBKIx+xEJJc79d1TmT2ROv2cqHaLMGpl11sxNO6x2Xw/hnig785ErE+v7AnWOfYyqvTGlAksbJLezJO3Jt4hlK6q7DDwkC9YAAMc09xd+cNKxyBNs9gwfuoc14d4IFjAjUj6+QF7IlkPCXkzhApYhbxG57dGUiKh7WmkMwEv0NraLNsmzGtmx1rRlmgaprf/nktTlarAzNI/mlH7Uju1YYqFUQuo7T4vPXcS4BUNpCUJEfqPnZs6xuraAbFhJkea5pa5iZImIN13VNOngAn4buzK/wErt4sdSJPEbY8eQgr91mrhop1GMXXAxflAlY4/TEa0pc+twJzDhfxzBpbM6/DPGeuZSzKnI6NZJLW1gHsEvnE1UUdsF0F4J5OLjPPYvLsiYCHV0wtBuWcVjdQ1LdaDY
  template:
    metadata:
      name: cloudflared-cloudflare-tunnel-remote
      namespace: cloudflared
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
