---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBM3EEjoCtQeoE2cgnHTjJcsmPAvrLBhgrdVPQ+ja+jrMEckkn0l/QGlU69dAy+IVGpsKuLZ1ODl892oAr7x9kLNkMWX3aihWf87QPDHM9JSFzF5VK64OF/LKgPAKAV/9J759EOElu039EVUL5tC/AmbvIb2Gso8r2W3avQYrXKErWTR1kY6BgFgpRSqbgq+ISQR05dlEJ7RT4FA6qhMe6BJvkpf1wuf9nWG7e7GPse1zkkzB5db1tQARQC66FmTCTcjt1JvK1HeAe8EVLyYCGNp51n9tEx0bseSKcV1J8w3XVK3xXsQuucmNXdBjVKDjnd87LposTlu0HGr6ZTNiZE/PKMRkOhth9hzWSFFqxT0otWt4Ez6H8fmgQfCquOhbBFtroUBAxIPA+4nPTiJ5RgWFjpy+bdkMxo71GZDhAT6g7g3WbLuc2B3q3UCHxoTt4akNGQ2UJe6mz1BxQx8Ztgt/wznE/5wkbWEl4e14bbjKKk/fYpJ1JEmnikqixpl4wVwoAClcfgj9F43wsDnxeQ+GnRc7uzfFW4C7MuInQFunUd4bVunE6QRUkrdkakz3W4wJFIi9NS4WIz+1AF2mSvFbfswCAA9v4Xdgl6Yo7w2LsWdhqV3orjKk9Gbm96Tnmnq6iwGA/2GF7wunsoqua0lLF8vMLYeAXz98/7AiKMiRfRndN2G3OcMEWS9nCbanOC/BWACrE7atIcVad+nTfe6ICQ6IAz3laJyTO3LDuu+nCFT7hqUke6zhl/nZLpQzphsJWP1S+brWumCi2BShMvvxmZ73y4+rP8dwU35BBHNXoPv7KG70utwOQqrIjOYETeEKLd56A+XXw4V5M9EFQakfonuJShr/tmXKmu4bDY20tGY3yMVnxmRZYL6qu4ZLfRnA+QPvCr/EOaH3abeCC+veujY94xMjdzgI03UmF5/w2+1NGykQ/T
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: cloudflared